name: 'CycloneDX Python Generate SBOM'
author: Patrick Dwyer
description: 'Github action to generate a CycloneDX BOM for Python projects'
inputs:
  input:
    description: 'The path to a pip requirements file'
    default: ./requirements.txt
    required: false
  output:
    description: 'Output filename'
    default: ./bom.xml
    required: false
runs:
  using: 'node12'
  main: 'index.js'
